### ISSUE TITLE
Hitting "back" on MyProfile sends to SignUp where one may SignUp again

### ISSUE THREAD

**Issue by AdamGualberta** [CMPUT301W16T16/GlamorousBorrowingWhaleApp#7]
This creates a new user that is "identical" to the current.
Please fix. Should not be able to go to sign up from MyProfile view.

**Comment by LSouthwell** [comment]
I think it would be okay to just disable the back button on that page? (since we'll be having a sign out button in the toolbar, going back doesn't need to do anything)

Google yielded this:

`@Override
public void onBackPressed()
{

   // super.onBackPressed(); // Comment this super call to avoid calling finish()
}`
